[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pymilk"

version = "1.5"
dependencies = ["pycryptodome", "pymongo", "pymysql", "aiomysql"]
keywords = ["pymilk", "layDB", "ORM", "mysql", "MongoDB", "Lsdict"]

readme = "README.md"
description = "一个开源的 Python 编程工具箱"
authors = [{name = "jutooy", email = "jutooy@qq.com"}]
classifiers = ["License :: OSI Approved :: Apache Software License"]
dynamic = []

[project.urls]
Docs = 'https://www.yuque.com/jutooy/pymilk'
Gitee = 'https://gitee.com/jutooy/pymilk'
Home = 'https://www.yuque.com/jutooy'
