[tool.poetry]
name = "pynatrace"
version = "1.3.0"
description = "Send logs to dynatrace via API"
authors = ["Michael MacKenna <mmackenna@unitedfiregroup.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.27.1"
click = "^8.1.3"
termcolor = "^1.1.0"
dt = "^1.1.48"

[tool.poetry.dev-dependencies]
pylint = "^2.13.9"

[tool.poetry.scripts]
pynatrace = 'pynatrace.cli:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
