[tool.poetry]
authors = ["Daven Quinn <dev@davenquinn.com>"]
description = "Core utilities for Sparrow"
name = "macrostrat.utils"
packages = [
  {include = "macrostrat"},
]
version = "1.0.1"

[tool.poetry.dependencies]
colorlog = "^6.5.0"
python = "^3.8"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
