[tool.poetry]
name = "exfill"
version = "0.1.17"
description = "A small app to grab job postings from online job boards"
authors = ["jay-law <jay-law@users.noreply.github.com>"]
readme = "README.md"
homepage = "https://github.com/jay-law/job-scraper"
repository = "https://github.com/jay-law/job-scraper"
documentation = "https://github.com/jay-law/job-scraper"

[tool.poetry.scripts]
cli-script = "src.exfill.extractor:main"

[tool.poetry.dependencies]
python = "^3.8"
black = "^22.3.0"
bs4 = "^0.0.1"
pandas = "^1.4.2"
selenium = "^4.1.5"
setuptools-scm = "^6.4.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ['py38']
line-length = 79
include = '\.pyi?$'

[tool.isort]
src_paths = ["src"]
py_version = 38
profile = "black"

[tool.mypy]
python_version = "3.8"
files = ['src/']