[package]
name = "spongebobizer"
version = "0.4.1"
description = "Command-line utility that outputs its stdin, converted to 'sPonGeBoB cAsE', and a library to support it"
license = "MIT"
repository = "https://gitlab.cronce.io/foss/spongebobizer"
authors = ["Mike Cronce <mike@quadra-tec.net>"]
edition = "2021"

[profile.dev]
debug = 1

[profile.release]
debug = 1
panic = "abort"
# false ("thin-local" LTO) is the default, but setting it explicitly because it produces a
# drastically faster binary for this project than thin or fat LTO - anywhere from 6.7-36.7%
# depending on the benchmark.
lto = false

[dependencies]
unicode-case-mapping = "0.3.0"

[dev-dependencies]
criterion = "0.3.5"
criterion-macro = "0.3.4"
focaccia = "1.1.2"
proptest = { version = "1.0.0", default-features = false, features = ["std"] }
test-strategy = "0.2.0"

[[bench]]
name = "benchmark"
harness = false

