[tool.poetry]
name = "pycountstutorial"
version = "0.3.1"
description = "Calculate word counts in a text file."
authors = ["PyCountsTutorial Developers"]
license = "BSD 3-Clause"
readme = "README.md"
homepage = "https://github.com/estripling/pycountstutorial"

[tool.poetry.dependencies]
python = "^3.8"
matplotlib = "^3.5.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
black = {extras = ["jupyter"], version = "^22.3.0"}
isort = "^5.10.1"
flake8 = "^4.0.1"
jupyter = "^1.0.0"
myst-nb = "^0.15.0"
sphinx-autoapi = "^1.8.4"
sphinx-rtd-theme = "^1.0.0"
python-semantic-release = "^7.29.0"

[tool.semantic_release]
version_variable = "pyproject.toml:version"
branch = "main"
changelog_file = "CHANGELOG.md"
build_command = "poetry build"
dist_path = "dist/"
upload_to_release = true
upload_to_pypi = false
remove_dist = false
patch_without_tag = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
